### ISSUE TITLE
Multipe dex files error when compiling

### ISSUE THREAD

**Issue by ghost** [RadiusNetworks/bluetooth-crash-resolver#2]
Not sure if this is a bug in Eclipse or something about the crash resolver. When I create the package com.radiusnetworks.bluetooth and add the BluetoothCrashResolver.java file, my compiles break on this error:

[2014-05-05 14:06:50 - Dex Loader] Unable to execute dex: Multiple dex files define Lcom/radiusnetworks/bluetooth/BluetoothCrashResolver$1;
[2014-05-05 14:06:50 - TreinBeacon] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lcom/radiusnetworks/bluetooth/BluetoothCrashResolver$1;

The most common explanation for this type of error is that some library already contains a class by the same name. Couldn't find one, but then I am fairly new to Eclipse and Android Java.

**Comment by davidgyoung** [comment]
If you are using the Android iBeacon Library, this class is already included, which would cause the problem you describe.

**Comment by ghost** [comment]
Thanks David! But now I'm confused: if it's already included, how come the crash still occurs? Is the idea that I still need to manually use this class's start() and stop() in my app as described in Radius Network's Bluetooth Crash resolved that Estimote has referenced here? 
https://github.com/Estimote/Android-SDK/issues/44

**Comment by davidgyoung** [comment]
If you are using the Android iBeacon Library version 0.7.6  for all Bluetooth LE scanning, then you do not need to do anything more to configure the crash resolver.  If you are also using other libraries or apps that do bluetooth LE scanning, then these may generate crashes independently, which will not be prevented by the crash resolver (although the crash resolver can clear the condition after they happen.)
