### ISSUE TITLE
Not working on Samsung Galaxy S4 running Android 4.3

### ISSUE THREAD

**Issue by darrenireland-bluecats** [RadiusNetworks/bluetooth-crash-resolver#3]
I am still getting the "Unfortunately, Bluetooth Share has Stopped" error message when I try to Force Flush. I have also tried adding the BluetoothCrashResolver code to my app with the same results. This does work on a Nexus 5 running Android 4.4.2

**Comment by rileyackerman** [comment]
I have experienced the same errors on an HTC One when attempting to flush. The only remedy I have found is a factory reset of the device.

**Comment by darrenireland-bluecats** [comment]
Ugh. I'm trying to avoid a factory reset, such a hassle. I guess if it works then at least its a solution.

**Comment by davidgyoung** [comment]
Darren,

I have a Nexus 5 as well, so I am surprised you are having trouble.  Make
sure no other apps are running that are doing BLE scans in the background
when you force flush.

Thanks,
David

**Comment by darrenireland-bluecats** [comment]
Its the Samsung Galaxy S4 that isn't working. The Nexus 5 is working. I was just letting you know that I tried the code on 2 different devices just to confirm it was the device and not the code. I suspect the Galaxy S4 has a smaller cache or something and so the limit is still being hit.

**Comment by darrenireland-bluecats** [comment]
I have done a factory reset on my Samsung Galaxy S4 and I have not experienced the issue since. Hopefully things are ok now.
