### ISSUE TITLE
App insists I turn off other apps using bluetooth. Would it be possible to list which apps are using bluetooth?

### ISSUE THREAD

**Issue by liminal** [RadiusNetworks/bluetooth-crash-resolver#5]
Just getting the message "Turn off other apps using bluetooth" is just about useless without a good way of finding out which apps are using bluetooth. 

If it is at all possible to add functionality to say... list apps that have  <uses-permission android:name="android.permission.BLUETOOTH" /> that would be a huge help I think.

**Comment by davidgyoung** [comment]
Fair point.  It should be possible to augment the standalone app to provide this info using the technique described here:  http://stackoverflow.com/a/4409222/1461050

If you'd like to volunteer to make this addition, I'd welcome a pull request.
